---
title: "Step 1: Create EML"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Required libraries
```{r}
library("dataone")
library("datapack")
library("EML")
```

Create baseline metadata file in EML for a data package which will be used to create and publish a data package in DataONE
```{r}
geographicDescription <- "Chicago"
coverage <- set_coverage(begin='2018-06-06', end='2018-06-06', geographicDescription=geographicDescription, west=-87.623177, east=-87.623177, north=41.881832, south=41.881832)
person <- as.person("Seokki Lee <slee195@hawk.iit.edu> [cre]")
slee <- as(person, "creator")
contact <- new("contact", individualName = slee@individualName, electronicMail = slee@electronicMailAddress, organizationName = "IIT", phone="000-000-0000")
pubDate <- "2018-06-06"
title <- "test from WT to DataONE"
abstract <- "test abs"
dataset <- new("dataset", title=title, creator=slee, pubDate=pubDate, abstract=abstract, coverage=coverage, contact=contact)
eml <- new("eml", system="uuid", dataset=dataset)
eml
write_eml(eml, "test.xml")
eml_validate("test.xml")
```


