---
title: "Recordr for a hydrocarbons use case"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* A use case package: https://search.dataone.org/#view/urn:uuid:3249ada0-afe3-4dd6-875e-0f7928a4c171

* Record provenance from R script 
```{r}
library(recordr)
rc <- new("Recordr")
record(rc, system.file("extdata/AOOS/Total_PAH_and_Alkanes_GoA_Hydrocarbons_Clean.R", package="recordr"), tag="aoos test")
```

* list and view provenance
```{r}
listRuns(rc)
viewRuns(rc)
```

* Provenance information for the script "Total_PAH_and_Alkanes_GoA_Hydrocarbons_Clean.R" from Recordr
```{r}
##[used]: 4 items used by this run
##-----------------------------------
##Location                                                     Size (kb)    Modified time      
##/Library/Frameworks/R.framew.../recordr/extdata/AOOS/PAH.csv 5525560      2018-06-11 12:52:39
##/Library/Frameworks/R.framew...cordr/extdata/AOOS/Alkane.csv 3932743      2018-06-11 12:52:38
##/Library/Frameworks/R.framew...cordr/extdata/AOOS/Sample.csv 1500015      2018-06-11 12:52:39
##/Library/Frameworks/R.framew...xtdata/AOOS/Non-EVOS_SINs.csv 3545         2018-06-11 12:52:39
##
##[generated]: 1 items generated by this run
##-----------------------------------------
##Location                                                     Size (kb)    Modified time      
##/private/var/folders/7t/xdmt...otal_Aromatic_Alkanes_PWS.csv 2881811      2018-06-13 20:11:44
```

* Enviornment information captured
```{r}
##[details]: Run details
##----------------------
##"/Library/Frameworks/R.framework/V...d_Alkanes_GoA_Hydrocarbons_Clean.R" was executed on 2018-06-13 20:11:30 CDT
##Tag: "aoos test"
##Run sequence #: 2
##Publish date: Not published
##Published to: NA
##Published Id: NA
##View at: NA
##Run by user: eunjungpark
##Account subject: NA
##Run Id: urn:uuid:27bfddb6-e086-4efe-942c-e914409d114b
##Data package Id: urn:uuid:b855ae57-534c-4c9a-9b45-631d3e95fd3f
##HostId: eunjeong-bag-ui-MacBook-Pro.local
##Operating system: x86_64-apple-darwin13.4.0
##R version: R version 3.3.3 (2017-03-06)
##Dependencies: stats, graphics, grDevices, utils, datasets, methods, base, spam_2.1-2, purrr_0.2.4, lattice_0.20-34, colorspace_1.3-2, hash_2.2.6, yaml_2.1.16, base64enc_0.1-3, blob_1.1.0, XML_3.98-1.9, rlang_0.2.1, pillar_1.2.3, foreign_0.8-67, glue_1.2.0, withr_2.1.2, DBI_1.0.0, rappdirs_0.3.1, bit64_0.9-7, uuid_0.1-2, bindr_0.1, stringr_1.2.0, dotCall64_0.9-5, fields_9.0, munsell_0.4.3, commonmark_1.4, gtable_0.2.0, mapproj_1.2.6, datapack_1.3.1, memoise_1.1.0, labeling_0.3, maptools_0.9-2, curl_3.2, Rcpp_0.12.14, openssl_1.0.1, scales_0.5.0, redland_1.0.17-9, jsonlite_1.5, bit_1.1-12, hms_0.4.0, digest_0.6.15, stringi_1.1.6, parsedate_1.1.3, grid_3.3.3, tools_3.3.3, maps_3.3.0, magrittr_1.5, lazyeval_0.2.1, tibble_1.4.2, RSQLite_2.0, EML_1.0.1, pkgconfig_2.0.1, xml2_1.2.0, assertthat_0.2.0, roxygen2_6.0.1, httr_1.3.1, R6_2.2.2, git2r_0.21.0, plyr_1.8.4, RColorBrewer_1.1-2, rgdal_1.3-2, rworldxtra_1.01, rworldmap_1.3-7, devtools_1.13.5, sp_1.3-1, bindrcpp_0.2, dplyr_0.7.4, raster_2.6-7, dataone_2.1.0, recordr_1.0.3.9000, tidyr_0.8.1, readr_1.1.1, ggplot2_2.2.1
##Run start time: 2018-06-13 20:11:30 CDT
##Run end time: 2018-06-13 20:11:44 CDT
##Error message from this run: NA
```
