---
title: "Recordr simulation for a use case"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* Record provenance from R script 
```{r}
library(recordr)

rc <- new("Recordr")
record(rc, system.file("./extdata/analysis.R", package="recordr"), tag="usecase run")
```

* list and view provenance
```{r}
listRuns(rc)
viewRuns(rc)
```

* Provenance information from Recordr
```{r}
## [details]: Run details
## ----------------------
## "/Library/Frameworks/R.framework/V...library/recordr/extdata/analysis.R" was executed on 2018-06-08 12:54:46 CDT
## Tag: "usecase run"
## Run sequence #: 4
## Publish date: Not published
## Published to: NA
## Published Id: NA
## View at: NA
## Run by user: eunjungpark
## Account subject: NA
## Run Id: urn:uuid:e2825b68-c9f7-402e-b7b7-f7c650e84e1e
## Data package Id: urn:uuid:dea88949-ab53-4b09-8f6e-7cc3fd09d2d1
## HostId: eunjeong-bag-ui-MacBook-Pro.local
## Operating system: x86_64-apple-darwin13.4.0
## R version: R version 3.3.3 (2017-03-06)
## Dependencies: stats, graphics, grDevices, utils, datasets, methods, base, Rcpp_0.12.14, pillar_1.2.3, plyr_1.8.4, tools_3.3.3, digest_0.6.15, uuid_0.1-2, bit_1.1-12, RSQLite_2.0, memoise_1.1.0, tibble_1.4.2, gtable_0.2.0, lattice_0.20-34, pkgconfig_2.0.1, rlang_0.2.1, DBI_1.0.0, datapack_1.3.1, commonmark_1.4, yaml_2.1.16, EML_1.0.1, stringr_1.2.0, roxygen2_6.0.1, xml2_1.2.0, rappdirs_0.3.1, hms_0.4.0, bit64_0.9-7, redland_1.0.17-9, grid_3.3.3, glue_1.2.0, R6_2.2.2, hash_2.2.6, XML_3.98-1.9, sp_1.3-1, purrr_0.2.4, blob_1.1.0, magrittr_1.5, scales_0.5.0, colorspace_1.3-2, labeling_0.3, stringi_1.1.6, lazyeval_0.2.1, munsell_0.4.3, tidyr_0.8.1, readr_1.1.1, raster_2.6-7, ggplot2_2.2.1, recordr_1.0.3.9000
## Run start time: 2018-06-08 12:54:46 CDT
## Run end time: 2018-06-08 12:54:48 CDT
## Error message from this run: NA
## 
## [used]: 1 items used by this run
## -----------------------------------
## Location                                                     Size (kb)    Modified time      
## /Library/Frameworks/R.framew...ry/recordr/extdata/mtcars.csv 1281         2018-06-08 12:48:04
## 
## [generated]: 2 items generated by this run
## -----------------------------------------
## Location                                                     Size (kb)    Modified time      
## /private/var/folders/7t/xdmt...tmpENC3tP/mtcars_gathered.csv 5401         2018-06-08 12:54:47
## /private/var/folders/7t/xdmt...0gn/T/RtmpENC3tP/mtcars_g.png 79487        2018-06-08 12:53:03
```

