---
title: "Step 2: Create a data package"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* Required libraries (it does not have to be reloaded as done in Step 1)
```{r}
library("dataone")
library("datapack")
library("EML")
```


* Create a data package which includes at least a metadata (EML generated above), source, program, output object.
```{r}
dp <- new("DataPackage")
```

Add the metadata file created in Step 1 into a package
```{r}
emlFile <- system.file("test.xml", package="dataone")
metadataObj <- new("DataObject", format="eml://ecoinformatics.org/eml-2.1.1", filename="test.xml")
dp <- addMember(dp, metadataObj)
```

Add source, program script, and output object into the package
```{r}
sourceObj <- new("DataObject", 
                 format="text/plain",
                 filename="/home/shek21/Documents/dataone/testArctic/rm-child2/test_child2_object")
dp <- addMember(dp, sourceObj, metadataObj)

progObj <- new("DataObject", 
               format="application/R",
               filename="/home/shek21/Documents/dataone/testArctic/rm-child2/copy_testChild2.R")
dp <- addMember(dp, progObj, mo=metadataObj)

outputObj <- new("DataObject", 
                 format="text/plain",
                 filename="/home/shek21/Documents/dataone/testArctic/rm-child2/test_child2_copied_object")
dp <- addMember(dp, outputObj, mo=metadataObj)
```


* Console Output
```{r}
## Members:
## 
## filename        format    mediaType  size     identifier    modified local 
## copy_t...ild2.R app...n/R NA         156      urn:u...7660e n        y     
## test_c...object tex...ain NA         54       urn:u...8066f n        y     
## test.xml        eml...1.1 NA         1777     urn:u...78e4a n        y     
## test_c...object tex...ain NA         54       urn:u...fcc23 n        y     
## 
## Package identifier: NA
## RightsHolder: NA
## 
## 
## Relationships (updated):
## 
##                 subject           predicate                object
## 4     copy_testChild2.R cito:isDocumentedBy              test.xml
## 2    test_child2_object cito:isDocumentedBy              test.xml
## 6 test_chil...ed_object cito:isDocumentedBy              test.xml
## 3              test.xml      cito:documents     copy_testChild2.R
## 1              test.xml      cito:documents    test_child2_object
## 5              test.xml      cito:documents test_chil...ed_object
```